Enable code coverage, check styles, and spot bugs
ballerina-platform/module-ballerinax-mysql pull request #61
Opened 2021-01-29 20:44 UTC by lahirusamith

## Purpose
> This is to Enable code coverage, check styles, and spot bugs

2021-01-29 20:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/module-ballerinax-mysql?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/module-ballerinax-mysql?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/module-ballerinax-mysql?pullRequest=61) it.</sub>

2021-01-30 03:36 UTC, BuddhiWathsala requested changes

2021-01-30 03:36 UTC, BuddhiWathsala commented on build-config/checkstyle/build.gradle
> + * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
We don't need to change the year if that file is already there. Please check.

2021-01-30 03:36 UTC, BuddhiWathsala commented on build.gradle
> + * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

2021-01-30 14:01 UTC, BuddhiWathsala requested changes

2021-01-30 14:01 UTC, BuddhiWathsala commented on build-config/checkstyle/build.gradle
> + * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

2021-01-30 14:01 UTC, BuddhiWathsala commented on build-config/spotbugs-exclude.xml
> +</FindBugsFilter>
```suggestion
</FindBugsFilter>

```

2021-01-30 14:04 UTC, BuddhiWathsala requested changes

2021-01-30 14:04 UTC, BuddhiWathsala commented on mysql-ballerina/build.gradle
> +        if (graph.hasTask(':sql-ballerina:build')) {
```suggestion
        if (graph.hasTask(':mysql-ballerina:build')) {
```

2021-01-30 14:04 UTC, BuddhiWathsala commented on mysql-ballerina/build.gradle
> +        if (graph.hasTask(':sql-ballerina:test')) {
```suggestion
        if (graph.hasTask(':mysql-ballerina:test')) {
```

2021-02-01 06:38 UTC, ThisaruGuruge commented on .github/workflows/pull-request.yml
> +          if-no-files-found: ignore
```suggestion
```

2021-02-01 08:28 UTC, BuddhiWathsala approved these changes

2021-02-01 08:31 UTC, BuddhiWathsala requested changes

2021-02-01 08:31 UTC, BuddhiWathsala commented on mysql-native/build.gradle
> + * Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

2021-02-01 08:34 UTC, BuddhiWathsala approved these changes

2021-02-01 08:52 UTC, merged